### ISSUE TITLE
Typo in readme 10-fundamentals/10-fundamentals.adoc

### ISSUE THREAD

**Issue by mihaita-tinta** [odrotbohm/spring-modulith-deep-dive#1]
`{spring-modulith-version}` should be `${spring-modulith-version}` in [10-fundamentals/10-fundamentals.adoc](https://github.com/odrotbohm/spring-modulith-deep-dive/blob/85b2852d037c8b55e0e7f3e7fdf574be839eb449/10-fundamentals/10-fundamentals.adoc?plain=1#L29)

**Comment by mihaita-tinta** [comment]
Opened PR [here](https://github.com/odrotbohm/spring-modulith-deep-dive/pull/2/)

**Comment by odrotbohm** [comment]
As explained in the PR, this is not a typo but a variable being replaced by the Asciidoctor rendering process.
